# -*- coding: utf-8 -*-
# Deployment settings for PatriotMissileDefense.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.3/s3e/makefile_builder/mkb.py', '--use-temp-extension', '--verbose=1', '--buildenv=VC11XWP', '--buildenv-toolset=WP8DEV', 'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/PatriotMissileDefense.mkb', '--deploy-only']
mkb = 'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/PatriotMissileDefense.mkb'
mkf = ['c:\\marmalade\\6.3\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.3\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.3\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.3\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\6.3\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.3\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.3\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\users\\pietro\\documents\\github\\patriot-missile-defense\\patriotmissiledefense.mkf']

class DeployConfig(object):
    os = ['wp8']
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense\data', '.', 0),
]

assets['default'] = [
    ('c:/users/pietro/documents/github/patriot-missile-defense/data/splashscreen.jpg', 'splashscreen.jpg', 0),
    ('c:/users/pietro/documents/github/patriot-missile-defense/data-ram/data-gles2-dx11/resources.group.bin', 'resources.group.bin', 0),
]

assets['artbuild'] = [
    ('c:/users/pietro/documents/github/patriot-missile-defense/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    os = ['wp8']
    embed_icf = -1
    name = 'PatriotMissileDefense'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Patriot Missile Defense'
    long_caption = 'Patriot Missile Defense'
    version = [0, 1, 0]
    config = ['c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/data/app.icf']
    data_dir = 'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/data'
    iphone_link_lib = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    wp8_author = 'Pietro Lorefice'
    iphone_link_libdirs = []
    splashscreen = 'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/data/splashscreen.jpg'
    wp8_description = 'A retro shooting game'
    iphone_link_opts = []
    provider = 'Pietro Lorefice'
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    icon = 'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/icons/icon.png'
    win32_ext_dll = []
    android_so = []
    osx_ext_dll = []
    iphone_link_libs = []
    wp8_publisher_id = '{ddb16f06-a317-4cd1-904a-2dfd55808386}'
    target = {
         'wp8-x86' : {
                   'debug'   : r'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/build_patriotmissiledefense_vc11xwp_wp8devtoolset/Debug_PatriotMissileDefense_VC11XWP_WP8DEVTOOLSET_x86/PatriotMissileDefense.s86',
                   'release' : r'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/build_patriotmissiledefense_vc11xwp_wp8devtoolset/Release_PatriotMissileDefense_VC11XWP_WP8DEVTOOLSET_x86/PatriotMissileDefense.s86',
                 },
         'wp8-arm' : {
                   'debug'   : r'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/build_patriotmissiledefense_vc11xwp_wp8devtoolset/Debug_PatriotMissileDefense_VC11XWP_WP8DEVTOOLSET_arm/PatriotMissileDefense.s86',
                   'release' : r'c:/Users/Pietro/Documents/GitHub/Patriot-Missile-Defense/build_patriotmissiledefense_vc11xwp_wp8devtoolset/Release_PatriotMissileDefense_VC11XWP_WP8DEVTOOLSET_arm/PatriotMissileDefense.s86',
                 },
        }
    assets = assets['default']

default = DefaultConfig()

######### Configuration: default

c = DeployConfig()
config['default'] = c
c.os = ['wp8']
c.target_folder = 'default'
c.icon = 'c:/users/pietro/documents/github/patriot-missile-defense/icons'
c.assets = assets['default']

######### Configuration: artbuild

c = DeployConfig()
config['artbuild'] = c
c.os = ['wp8']
c.target_folder = 'artbuild'
c.assets = assets['artbuild']
